# Generated by Django 2.1.7 on 2019-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
