# Generated by Django 2.1.7 on 2019-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
