# Generated by Django 2.1.7 on 2019-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
    ]
